---
- name: Secure SSH
  hosts: all
  tasks:
    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      become: yes
    - name: restart ssh
      service:
        name: sshd
        state: started
        become: yes
        
