---
- name: Secure SSH
  hosts: $hosts
  tasks:
    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
    - name: restart ssh
      service:
        name: sshd
        state: started
